doctrine_migrations:
    organize_migrations: BY_YEAR_AND_MONTH
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        'App\Interfaces\Gateways\Doctrine\Migrations': '%kernel.project_dir%/src/Interfaces/Gateways/Doctrine/Migrations'
    enable_profiler: '%kernel.debug%'
