nelmio_api_doc:
    documentation:
        info:
            title: My App
            description: This is an awesome app!
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
    areas: # to filter documented areas
        default:
            path_patterns:
                - ^/api(?!/doc|login_check$) # Accepts routes under /api except /api/doc and /api/login_check
